### ISSUE TITLE
Link the Hacktober fest header logo to home 

### ISSUE THREAD

**Issue by Hardikag17** [dsc-jiit-128/Hacktoberfest_Website#1]
**Hactober fest** header logo cursor type should be pointer and should be linked to home.

**Comment by Haniket** [comment]
I want to work on it.....

**Comment by rishavjaiss** [comment]
I can do this!

**Comment by Hardikag17** [comment]
@rishavjaiss and @Haniket guys you both can work on it , the one who opens a Pull Request first will be considered :)

**Comment by Castella1313** [comment]
@Hardikag17 I guess it would be a great idea to assign the issue to that contributor who asked for it first and should be given a deadline of like 4 days. If that contributor won't be able to solve it in 4 days the issue will be assigned to the next person in the queue.
I only meant to say, putting the contributors in queue, because assigning the same issue to two different contributors at the same time will waste the time only.

**Comment by Haniket** [comment]
@Hardikag17 plz clarify who have to work on it first......

**Comment by Castella1313** [comment]
@rishavjaiss you have been added to queue.

**Comment by Castella1313** [comment]
@Haniket how much time you want to get this issue resolved? :)

**Comment by Haniket** [comment]
@Castella1313 it is labelled as hacktoberfest so can I make pr on 1 october...
thanks

**Comment by Hardikag17** [comment]
@Haniket sure go ahead make PR before 1st October midnight.

**Comment by Haniket** [comment]
@Hardikag17 sir I just have a little question that if I make PR before 1october midnight will it be counted for hacktoberfest 2020??

**Comment by Castella1313** [comment]
@Haniket yes, every issue labelled with Hacktoberfest will be counted for the Hacktoberfest, its just that your PR should be merged in October, otherwise you can create PRs from now itself.

**Comment by Hardikag17** [comment]
@Haniket you have to make your PR in October month to make it count for hactoberfest.
also go through all the participation details [here](https://hacktoberfest.digitalocean.com/details/) and yeah you also need to sign up on hactoberfest official site then only your PRs count ,sign up process will start from 1st October.

**Comment by ventodeco** [comment]
whether to submit PR for this issue must be the person assigned sir? @Hardikag17

**Comment by Haniket** [comment]
had also completed the issue just waiting for 1st october for pr....

**Comment by Castella1313** [comment]
@ventodeco your PR won't be counted for Hacktoberfest.

**Comment by ventodeco** [comment]
oh so if we want to count on hacktoberfest must make PR on october, not now? how about PR that open now? @Haniket 
And if we not assign to that issues, can i just resolved it? or not? or i must ask to assign it to me?

**Comment by ventodeco** [comment]
sorry im new in it @Castella1313 , i will closed my PR

**Comment by ventodeco** [comment]
> @ventodeco your PR won't be counted for Hacktoberfest.

and if we not assign to that issues, can i just resolved it? or not? or i must ask to assign the issues to me? @Castella1313

**Comment by Haniket** [comment]
> oh so if we want to count on hacktoberfest must make PR on october, not now? how about PR that open now? @Haniket 


yes @ventodeco PR would be counted only in October as mentioned above by @Hardikag17 sir.....


> And if we not assign to that issues, can i just resolved it? or not? or i must ask to assign it to me?

I am also new so I don't know much but one have to ask first and then if it is assigned to him then he have to work on it...

**Comment by Castella1313** [comment]
@ventodeco this issue is already assigned to @Haniket already as he asked for it first. You are added to queue in case @haniket fails to solve the issue. So you must go for solving a issue once it is assigned to you.

**Comment by ventodeco** [comment]
oh okay, thanks for the information @Castella1313 @Haniket :)
