### ISSUE TITLE
Add a fixed footer to "about us" page

### ISSUE THREAD

**Issue by Castella1313** [dsc-jiit-128/Hacktoberfest_Website#15]
Add a fixed footer to "about us" page which would be similar to the footer of the home page.

Do create your pull request in a new branch, whose name should be in the format of "issue_no/file_changed".

**Comment by pranav2012** [comment]
#16 Just created a pull request, please review the changes and merge thank
you, Participating in Hacktober fest 2020

**Comment by Castella1313** [comment]
@pranav2012 we will be merging the PRs from 1st October :)

**Comment by pranav2012** [comment]
ok, please assign me for this issue thank you

**Comment by Castella1313** [comment]
@pranav2012 I suggest you to get the issue assigned first before creating the PR :) 
Happy coding :)

**Comment by Castella1313** [comment]
@pranav2012 It would be great if you create PR in a new branch from next time, its just a good practice :)

**Comment by pranav2012** [comment]
ok thank you, Sorry new to open Source

**Comment by Castella1313** [comment]
> ok thank you, Sorry new to open Source

your work is appreciated
KEEP LEARNING
Happy Coding :)))

**Comment by Castella1313** [comment]
@pranav2012 I hope you are well aware about the rules for participating in Hacktoberfest. PR must be made between 1st oct to 31st oct.

**Comment by pranav2012** [comment]
ok @Castella1313 I will make another on 1st, Thank you

**Comment by pallavithakare28** [comment]
@Castella1313 May I work on this issue?
