### ISSUE TITLE
Link The instagram icon and Github icon in footer

### ISSUE THREAD

**Issue by ads-22** [dsc-jiit-128/Hacktoberfest_Website#17]
Link The instagram icon and Github icon in footer to the given links.

Instagram :->>[https://www.instagram.com/dscj128/](url)
Github :->>[https://github.com/dsc-jiit-128](url)

**Comment by Haniket** [comment]
I want to work on it ......

**Comment by pranav2012** [comment]
just created a pull request on that #16

**Comment by Haniket** [comment]
@ads-22 can I add a little bit of overlay on footer because without a overlay one cannot find where the footer actually starts......so can I add that to footer

**Comment by ads-22** [comment]
@pranav2012 you have been added to queue for this issue.

**Comment by ads-22** [comment]
@pranav2012 We will be merging PR's in october !!

**Comment by ads-22** [comment]
@Haniket go ahead and give us your best output.
