### ISSUE TITLE
Add a link to About section from Explore button.

### ISSUE THREAD

**Issue by Hardikag17** [dsc-jiit-128/Hacktoberfest_Website#2]
Explore button on homepage does nothing ,add a link to **About Us** section from it.

**Comment by JoseRivera12** [comment]
https://github.com/dsc-jiit-128/Hacktoberfest_Website/pull/3

**Comment by shubhamgoel24** [comment]
Is this issue still open ?
Can i work on it ?

**Comment by rohan2734** [comment]
hi i would like to work on this issue.

**Comment by pranav2012** [comment]
Hey @Hardikag17, I would love to contribute

**Comment by Hardikag17** [comment]
Sorry  @shubhamgoel24  @rohan2734 @pranav2012  , @JoseRivera12 have already made a pull request first which I will review on 1st October ,as this particular project is for hacktober fest for encouraging you more and more towards open source so, reviewing of PRs will take place in October month. Until then, by going by the rule first come first serve @JoseRivera12 takes this issue. but we have opened lots of more beginner's issues do check them out.

**Comment by ventodeco** [comment]
can you assign this issues to me sir? @Hardikag17 thanks :)

**Comment by tanya4067** [comment]
Hey, I'd like to contribute

**Comment by Castella1313** [comment]
@JoseRivera12 have you been working on this issue?? There are other people too in the queue

**Comment by JoseRivera12** [comment]
@Castella1313 I made pull request

**Comment by JoseRivera12** [comment]
https://github.com/dsc-jiit-128/Hacktoberfest_Website/pull/62
