### ISSUE TITLE
The expansion should fade in and fade out within a specific time in FAQ'S Page.

### ISSUE THREAD

**Issue by ads-22** [dsc-jiit-128/Hacktoberfest_Website#20]
The expansion and Collapsing should fade in and fade out within a specific time in FAQ'S Page.
![Screenshot (10)](https://user-images.githubusercontent.com/70308797/94367015-62d64b80-00f9-11eb-9499-b49af0e434e5.png)
The + sign expand and collapses the section but this should go out smoothly.

**Comment by MukulTan10** [comment]
hey , can i work on this for hacktober2020?

**Comment by wolffshots** [comment]
I'm also interested in doing this for Hacktoberfest, I've got an initial working implementation on my fork but not sure if I should wait until Thursday to create a PR?

**Comment by ads-22** [comment]
@jadonwolffs  only the PR's made in the month of october will be counted. for more info just go through readme.md  file.

**Comment by ads-22** [comment]
@MukulTan10 you have time till 2nd october to make a PR after that issue will be assigned to the next person in the queue.

**Comment by wolffshots** [comment]
> @jadonwolffs only the PR's made in the month of october will be counted. for more info just go through readme.md file.

noted, thanks

**Comment by MukulTan10** [comment]
@ads-22  
hey, i have added pull request for the same issue
