### ISSUE TITLE
Fix hamburger menu button animation duration

### ISSUE THREAD

**Issue by rishipurwar1** [dsc-jiit-128/Hacktoberfest_Website#25]
**Describe the bug**
When we press on the hamburger menu button, it takes some time to open a menu on the mobile devices.
menu animation is slow

**To Reproduce**
Click on the navigation menu button to see a bug in the mobile device.

**Expected behavior**
It should be smooth and fast.

**Screenshots**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/57035408/94417590-e0ec2e00-019d-11eb-92aa-e33afe159a3a.gif)

**Desktop:**
Windows 10
Chrome

**Comment by rishipurwar1** [comment]
I would like to work on this issue.

**Comment by withlakshmanan** [comment]
@rishipurwar1 

Changes are done in the below PR.
https://github.com/dsc-jiit-128/Hacktoberfest_Website/pull/29

**Comment by rishipurwar1** [comment]
It's okay 
I'll close this pr..
