### ISSUE TITLE
Overflow in navigation menu in mobile devices

### ISSUE THREAD

**Issue by rishipurwar1** [dsc-jiit-128/Hacktoberfest_Website#26]
**Describe the bug**
When we open a website on a mobile device, there is an overflow-x in the navigation menu.

**Expected behavior**
There should not an overflow in the navigation menu

**Screenshots**
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/57035408/94417622-ec3f5980-019d-11eb-80c2-431c988bf7a2.gif)

**Desktop**
Windows 10
Chrome

**Comment by rishipurwar1** [comment]
I would like to work on this issue.

**Comment by Castella1313** [comment]
@rishipurwar1 sure!! Go a head.

**Comment by rishipurwar1** [comment]
Thanks for assigning me this issue...

**Comment by rishipurwar1** [comment]
I think this issue is fixed by someone. Please check it..

**Comment by Castella1313** [comment]
this issue has been resolved, so closing this issue!
