### ISSUE TITLE
Padding issue in the card

### ISSUE THREAD

**Issue by rishipurwar1** [dsc-jiit-128/Hacktoberfest_Website#27]
**Describe the bug**
In the card, there is not enough padding between the text.

**Do have a look at the readme before doing any contribution :)**

**Expected behavior**
There should be some padding between the text. It should look like this
![Shot 0002](https://user-images.githubusercontent.com/57035408/94418433-09285c80-019f-11eb-968e-6c76405b7cc1.png)

**Screenshots**
![Shot 0001](https://user-images.githubusercontent.com/57035408/94418428-075e9900-019f-11eb-8b10-174a0b2d91a4.png)

**Desktop (please complete the following information):**
Windows 10
Google Chrome

**Comment by rishipurwar1** [comment]
I am working on this issue.

**Comment by Castella1313** [comment]
@rishipurwar1 go ahead :)

**Comment by rishipurwar1** [comment]
Thanks for assigning me this issue...

**Comment by Pranay0803** [comment]
I would also like to work on this issue

**Comment by Castella1313** [comment]
@Pranay0803 you've been added to queue....

**Comment by rishipurwar1** [comment]
@Castella1313 I'll make a pr today...

**Comment by Castella1313** [comment]
@rishipurwar1 sure :)
