### ISSUE TITLE
Icons are too small in card section

### ISSUE THREAD

**Issue by rishipurwar1** [dsc-jiit-128/Hacktoberfest_Website#28]
**Describe the bug**
Icons size is too small and it is not clearly visible.

**To Reproduce**
1. Go to the card section
2. See error

**Do have a look at the readme before doing any contribution :)**

**Expected behavior**
It should be clearly visible. It should look like this.
![Shot 0004](https://user-images.githubusercontent.com/57035408/94419402-5953ee80-01a0-11eb-8d43-82800e86527a.png)

**Screenshots**
![Shot 0003](https://user-images.githubusercontent.com/57035408/94419267-227dd880-01a0-11eb-9a0d-6692b1c99c5e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome

**Comment by rishipurwar1** [comment]
I am working on this issue

**Comment by Castella1313** [comment]
@rishipurwar1 Go ahead :)

**Comment by rishipurwar1** [comment]
Thanks for assigning me this issue...

**Comment by GeekyNaved** [comment]
I have resolved this issue. Can I make pull request ?

**Comment by Castella1313** [comment]
@GeekyNaved firstly, you cannot start working on an issue unless it is assigned to you. Secondly, if you wanna make PR to participate in Hacktoberfest, you have to make PR between 1st oct to 31st oct.

**Comment by GeekyNaved** [comment]
sorry I am new to github that's why I've already made pull request.

**Comment by rishipurwar1** [comment]
I'll make a pr on 1st october

**Comment by rishipurwar1** [comment]
@GeekyNaved you should close your pr...

**Comment by GeekyNaved** [comment]
@rishipurwar1  ok

**Comment by rishipurwar1** [comment]
@Castella1313 Is this looks good
![2020-09-30 14_53_50-Greenshot](https://user-images.githubusercontent.com/57035408/94667821-ea57d080-032c-11eb-86f0-2682d82998e9.png)

**Comment by Castella1313** [comment]
@rishipurwar1 Yep !! Great work :)
