### ISSUE TITLE
Should include link in the navbar logo to home page

### ISSUE THREAD

**Issue by dsnehasish74** [dsc-jiit-128/Hacktoberfest_Website#32]
![Screenshot (280)_LI](https://user-images.githubusercontent.com/58779604/94654594-e4f18a80-031a-11eb-807b-eb30889f7cf8.jpg)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dsnehasish74** [comment]
Can you assign this work to me

**Comment by Castella1313** [comment]
@dsnehasish74 Go ahead :)

**Comment by Castella1313** [comment]
@dsnehasish74 this issue has already been mentioned i.e #1, so closing this issue
