### ISSUE TITLE
Overflow when page first loads in the hero section

### ISSUE THREAD

**Issue by rishipurwar1** [dsc-jiit-128/Hacktoberfest_Website#33]
**Describe the bug**
When the website first loads, overflow on the hero section occurs which is not good.

**To Reproduce**
1. Go to 'https://thehacktoberfest2020.netlify.app/'
4. See an error

**Expected behavior**
It should look like this
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/57035408/94663678-90084100-0327-11eb-9f95-544dcae66904.gif)

**Screenshots**
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/57035408/94663448-4fa8c300-0327-11eb-8ca3-22f6bed7bb9a.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome

**Comment by rishipurwar1** [comment]
I would like to work on this issue

**Comment by Castella1313** [comment]
@rishipurwar1 Yep!! Seems like a valid issue :) Go ahead!

**Comment by rishipurwar1** [comment]
Thanks @Castella1313 for assigning me this issue.

**Comment by rishipurwar1** [comment]
Should I create a separate branch for each issue or directly make a pr on the master branch.

**Comment by rishipurwar1** [comment]
Hello @Castella1313, I made a separate branch for each issue. Is it OK or not?

**Comment by Castella1313** [comment]
@rishipurwar1 yep :)
