### ISSUE TITLE
Fix the footer.

### ISSUE THREAD

**Issue by Hardikag17** [dsc-jiit-128/Hacktoberfest_Website#4]
Footer contents are not in well contrast with the background so make a separate background for it and make footer position fixed So, that Contacts information can be displayed on every page.

**Comment by zbolo** [comment]
Hi, I wish to work on that one 👍

**Comment by Lilykhan786** [comment]
Hey, can I improve the UI?

**Comment by Hardikag17** [comment]
@fbologni I am assigning this particular issue to you. make your PR in October month by 1st October midnight . As this project is for hacktoberfest specially .To encourage more and more people towards open source. if you don't have any knowledge about hactoberfest do check this out.   
[About hacktoberfest](https://hacktoberfest.digitalocean.com/)

**Comment by Hardikag17** [comment]
> Hey, can I improve the UI?

@Lilykhan786 yeah sure, absolutely. go ahead. make your PR we will review it and yeah make sure if you are participating in hacktoberfest then make your PR in October month.

**Comment by zbolo** [comment]
@Hardikag17 Pull request done. Let me know if color and dimensions are ok ;)
