### ISSUE TITLE
Place the parallax background image to centre for small screens

### ISSUE THREAD

**Issue by Castella1313** [dsc-jiit-128/Hacktoberfest_Website#43]
Place the parallax background image to centre for small screens

issue screenshot

**do make the pr in a separate branch**

![c58bde83-c067-44b5-b851-01df745bc77b](https://user-images.githubusercontent.com/53293156/94731757-ece51500-0382-11eb-8e88-b1b4fcf14289.jpg)

**Comment by purnima143** [comment]
Can I work on this issue?

**Comment by Castella1313** [comment]
@purnima143 go ahead :)

**Comment by purnima143** [comment]
I have done with PR. Kindly check it.
