### ISSUE TITLE
The banner-title comes under the nav for screen-size less than 568px

### ISSUE THREAD

**Issue by Divyanshwick** [dsc-jiit-128/Hacktoberfest_Website#45]
### The banner title comes under the navbar for screen-size < 568px 
![2020-10-01](https://user-images.githubusercontent.com/57042143/94732236-9debaf80-0383-11eb-8777-12028ef60d92.png)

**Comment by Divyanshwick** [comment]
Please assign me this issue

**Comment by Castella1313** [comment]
@Divyanshwick is this really a problem??? Because its absolutely fine in my mobile
