### ISSUE TITLE
overlapping of cards with the navigation bar while scrolling

### ISSUE THREAD

**Issue by Castella1313** [dsc-jiit-128/Hacktoberfest_Website#5]
These cards are displaying above the navigation bar. 
Here is the sample of the problem with the cards:-

Do create your pull request in a new branch, whose name should be in the format of "issue_no/file_changed".

**Do have a look at the readme before doing any contribution :)**

![200950d6-c61e-4745-bb02-90edb596eac4](https://user-images.githubusercontent.com/53293156/94352347-6cbc6800-0081-11eb-83e3-7033b371ca81.jpg)

**Comment by swastikchugh** [comment]
Hey @Castella1313, I would like to contribute to this.

**Comment by Castella1313** [comment]
> Hey @Castella1313, I would like to contribute to this.

Go ahead

**Comment by rishipurwar1** [comment]
Is anyone is still working on this issue? If not I would like to work on it.

**Comment by Castella1313** [comment]
@rishipurwar1 this issue is assigned to @swastikchugh, if you wanna work, you can be added to queue and if no PR is made for this issue till 3rd oct, it will be assigned to you.

**Comment by swastikchugh** [comment]
Hey @Castella1313 
while pushing im getting permission denied error.
