### ISSUE TITLE
Apply parallax effect in the background of "about us" page

### ISSUE THREAD

**Issue by Castella1313** [dsc-jiit-128/Hacktoberfest_Website#6]
Apply parallax effect in the background of "about us" page. It's a kind of like keeping the background fixed that will beautify the UI.

Do create your pull request in a new branch, whose name should be in the format of "issue_no/file_changed".

**Do have a look at the readme before doing any contribution :)**

here is the sample screenshot of the issue:-

![ae2c2c66-15fa-4bb9-b69f-0a2d68042cd6](https://user-images.githubusercontent.com/53293156/94352516-8a8acc80-0083-11eb-95d7-f0e02632c038.jpg)

**Comment by dikshantmali** [comment]
Hey @Castella1313 I want to work on this issue so please assign it to me for hacktoberfest. I have already worked on parallax.

**Comment by Castella1313** [comment]
> Hey @Castella1313 I want to work on this issue so please assign it to me for hacktoberfest. I have already worked on parallax.

Go ahead :)

**Comment by dikshantmali** [comment]
@Castella1313 I have successfully added a parallax effect to the about us page. But I made PR in the month of October so that it can count in my hacktoberfest contribution.

**Comment by Castella1313** [comment]
@dikshantmali Great :) Do make a PR on 1st October. Do register for Hacktoberfest first!!

**Comment by dikshantmali** [comment]
Sure... Thanks for assigning this issue to me. Overall it is a good learning experience for me.

**Comment by dikshantmali** [comment]
@Castella1313 I have made a pull request please review and merge

**Comment by Castella1313** [comment]
@dikshantmali have you??

must mention the issue number you have resolved in your pr, i.e #6
