### ISSUE TITLE
The comment in CSS code is wrong.

### ISSUE THREAD

**Issue by Lilykhan786** [dsc-jiit-128/Hacktoberfest_Website#61]
The comment in CSS code is wrong. you have used html comment syntax in css file instead of css syntax

I have made a pr to fix that (wasn't knowing there should be issue to make the pr so i"m making this issue. thank you. #46

**Comment by priyankaagrawal123** [comment]
I am interested. I can implement.
Please assign this issue to me.

**Comment by Lilykhan786** [comment]
@priyankaagrawal123 its already fixed 
![image](https://user-images.githubusercontent.com/47777673/94895443-0c765d80-04a9-11eb-8ded-49f6b0207ae3.png)
