### ISSUE TITLE
organize files

### ISSUE THREAD

**Issue by nishu91020** [dsc-jiit-128/Hacktoberfest_Website#66]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Castella1313** [comment]
Can you please elaborate??

**Comment by Castella1313** [comment]
I guess the valid issue is "adding comments in the files for better understanding"

**Comment by nishu91020** [comment]
files were not organized in folders properly everything was in the main folder now I have bifurcated them in different folders like CSS,images, etc. and also modified the front page, for knowing more you can have a look at my pull request.

**Comment by nishu91020** [comment]
this will lead to a better understanding of the code.
