### ISSUE TITLE
Change "Events" To "Statistics" 

### ISSUE THREAD

**Issue by ads-22** [dsc-jiit-128/Hacktoberfest_Website#8]
Change the text Of "Events" in the Navbar to  "Statistics".

**Comment by dannylwe** [comment]
Hi, I would like to work on this issue

**Comment by ads-22** [comment]
Go ahead..

**Comment by shikhargupta-in** [comment]
I want to work on this issue! If @dannylwe is not doing! Please let me know.

**Comment by ads-22** [comment]
@dannylwe make PR by 07-10-2020 after that it will be assigned to next person.
