### ISSUE TITLE
Scroll Down To Statistics Section When Clicked On "Events" in Navbar.

### ISSUE THREAD

**Issue by ads-22** [dsc-jiit-128/Hacktoberfest_Website#9]
Scroll Down To Numbers (Statistics) Section When Clicked On "Events" in Navbar.

![Screenshot (7)](https://user-images.githubusercontent.com/70308797/94357432-81ffb980-00b6-11eb-97fb-fe636f55bdfa.png)

The "Events" at the navbar doesn't take us anywhere it should scroll the page down to Numbers (Statistics) section (section containing counts) as shown in the screenshot.

**Comment by ShubhamSood1406** [comment]
Can I do this?

**Comment by ads-22** [comment]
sure..Go ahead!!

**Comment by ShubhamSood1406** [comment]
@Castella1313 Can you close this issue? I have already send a PR for this on issue #40

**Comment by Castella1313** [comment]
Let it get merged first

**Comment by ShubhamSood1406** [comment]
Okay
